language: python
sudo: false
cache: pip

python:
  - "3.4"
  - "2.7"

branches:
  only:
    - master

# command to install requirements
install:
  - pip install https://github.com/nemesisdesign/django-organizations/tarball/master  # temporary
  - pip install https://github.com/openwisp/django-x509/tarball/master  # temporary
  - pip install https://github.com/openwisp/django-netjsonconfig/tarball/master  # temporary
  - python setup.py -q develop
  - pip install -r requirements-test.txt

before_script:
  - ./runflake8

# command to run tests, e.g. python setup.py test
script:
  - coverage run --source=openwisp2 runtests.py

after_success:
  coveralls
